### ISSUE TITLE
Should remove preserve-content attr when showing source

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-demo-helpers#10]
When user copy code, they don't need the preserve-content, only needed for making the demo work in the snippet

```
<dom-module id="my-horizontal-view">
  <template preserve-content>
```

**Comment by web-padawan** [comment]
We no longer showcase `dom-module` in the demos and aim to remove `<template>` support soon as well.
The `preserve-content` attribute is Polymer-specific, and not something we want to deal with. Closing.
