### ISSUE TITLE
Error activating current tab link on the first load

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-demo-helpers#11]
Firefox Quantum [got fast again](https://hacks.mozilla.org/2017/11/entering-the-quantum-era-how-firefox-got-fast-again-and-where-its-going-to-get-faster/)... so fast that even broke our demo snippet, especially [line 142](https://github.com/vaadin/vaadin-demo-helpers/blob/master/vaadin-component-demo.html#L142).

## Expected outcome:

The active link in the demo navigation should have `active` attribute.

## Actual outcome

The following error is thrown: 
```
TypeError: this.$.nav.querySelector(...) is null
```

## Steps to reproduce

1. serve any element demo locally (e. g. `vaadin-dropdown-menu`)
2. open demo page in Firefox 57
3. refresh the page (the error seems to be thrown occasionally)

So it seems that `setTimeout` in the related code should be replaced (or increased, but that would cause noticeable active link flash).

UPD: happens on Safari and Chrome as well.

**Comment by samiheikki** [comment]
I also remember seeing this earlier this week, but at least now I'm unable to reproduce this in Quantum (tried windows and mac). But was able to reproduce when I changed the `setTimeout` for 1 millisecond so it is definitely something with that nav querySelector.
