### ISSUE TITLE
The first tab item is not selected when opening the demos without a url fragment

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-demo-helpers#21]
For example, if you open https://vaadin.com/elements/vaadin-board/html-examples/, the “Basics” tab is open, but not highlighted.

<img width="920" alt="screen shot 2018-02-28 at 10 50 55" src="https://user-images.githubusercontent.com/66382/36778404-4833f2b6-1c75-11e8-85b8-887bf3ebe4e4.png">

After reloading the page (the URL has been updated with the fragment to https://vaadin.com/elements/vaadin-board/html-examples/board-basics), the tab is highlighted.

<img width="901" alt="screen shot 2018-02-28 at 10 51 49" src="https://user-images.githubusercontent.com/66382/36778465-70d3dea2-1c75-11e8-8da5-8433b2eea71c.png">

**Comment by web-padawan** [comment]
Most likely related to #11

**Comment by jouni** [comment]
Yeah, seems like the same issue. Happens on Safari and Chrome as well.

There’s also a nasty effect that the page is scrolled down to the examples when using the fragment URL.
