### ISSUE TITLE
Code in demo (IE11)

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-demo-helpers#39]
There is a weird behaviour of `vaadin-combo-box` demos in IE11.
It is showing extra code on second `demo-snippet`:
![screen shot 2018-07-17 at 15 22 03](https://user-images.githubusercontent.com/29372419/42816951-32197d48-89d5-11e8-8153-d227b2be902d.png)

**Comment by web-padawan** [comment]
We will stop using demo helpers after we have a new docs site. 
And vaadin.com that still uses these helpers no longer supports IE11.

So I guess we can close this.
