### ISSUE TITLE
Issues on Edge

### ISSUE THREAD

**Issue by tulioag** [vaadin/vaadin-demo-helpers#51]
I'm having a few issues on Edge. We updated the demos for vaadin-app-layout and we are getting syntax errors on Edge

![screenshot from 2018-09-04 16-17-51](https://user-images.githubusercontent.com/28783969/45036596-92731080-b065-11e8-8dd6-f8e2fd3ea631.png)

The "Waiting for 'set-template' message never goes away."

The same is happening on https://vaadin.com/router (scroll down for the demos).

On some other components, the demos do work, like https://vaadin.com/components/vaadin-tabs/html-examples/tabs-basic-demos, but in the console there are `"Unable to get the 'baseHref' from the vaadin-component-demo>"` error messages

**Comment by platosha** [comment]
Looks like it’s related to iframe demo snippet.

@vlukashov Could you please take a look?
