### ISSUE TITLE
Vaadin-demo-snippet "Copy" button can't be focused with keyboard in Safari 12

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-demo-helpers#57]
Demo: https://cdn.vaadin.com/vaadin-button/2.1.0/demo/#button-basic-demos

Try using tab and shift+tab. Copy button doesn't get focus ever

**Comment by web-padawan** [comment]
Works in Safari 12.0.3 on Mac OS Sierra. 
Tested via https://cdn.vaadin.com/vaadin-button/2.2.0/demo/#button-basic-demos
