### ISSUE TITLE
Expose the iframe content window when demo-iframe-renderer is in use

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-demo-helpers#60]
Use case: a `Vaadin.Router` demo using the baseUrl feature. For the particular demo, after the iframe document is loaded, I want to make a client-side navigation in the content window to some base URL instead of the default `/`.

Currently, accessing the content window for a demo snippet’s iframe is hard. Also, it is hard to get the timing right to invoke thins after load. The `iframeSrc` property does not help: it changes the iframes’s `src`, and this results in a full document reload.

Example workaround:

```
const baseUrlDemoSnippet = this.$['some-demo'];
const origShowDemo = baseUrlDemoSnippet._showDemo;
baseUrlDemoSnippet._showDemo = function() {
  origShowDemo.apply(this, arguments);
  const iframeDemoRenderer = baseUrlDemoSnippet.$.demo.firstElementChild;
  iframeDemoRenderer.__iframeReady.then(() => {
    iframeDemoRenderer.url = '/ui/';
    iframeDemoRenderer._postIframeMessage({type: 'set-url', url: '/ui/'});
  });
};
```

**Comment by web-padawan** [comment]
This repository is no longer maintained and will be archived.
